apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: berget-me
  namespace: berget-me
  annotations:
    kubernetes.io/ingress.class: nginx
    cert-manager.io/cluster-issuer: letsencrypt-prod
spec:
  tls:
  - hosts:
      - me.berget.ai
    secretName: berget-me-tls
  rules:
  - host: me.berget.ai
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: berget-me
            port:
              number: 80
