apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: berget-me
  namespace: berget-me
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    cert-manager.io/cluster-issuer: letsencrypt-prod
spec:
  rules:
  - host: me.berget.ai
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: berget-me
            port:
              number: 80
  tls:
  - hosts:
    - me.berget.ai
    secretName: berget-me-tls
